apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project-argocd
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: sandbox2748
    name: sandbox2748
    server: '*'
  sourceRepos:
  - '*'
